// compile.js — SINGLE SOURCE OF TRUTH for the MA3 command sequence.
// buildLua() (exported .lua plugin) and buildCmdLines() (live OSC) MUST emit the
// same sequence. Any change here must also update shared/ma3-command-spec.md in
// the same PR. Depends on: constants (POOLS, POOL_NUM), state, util (download).

// Collapse a free-text (often voice-captured, multi-line) note into one safe
// command-line token: newlines/tabs/runs of whitespace → single space, trimmed,
// then " escaped to \". Returns '' for null/empty/whitespace-only input.
function sanitizeNote(raw) {
  return String(raw == null ? '' : raw)
    .replace(/[\r\n\t]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/"/g, '\\"');
}

function songToLuaEntry(song) {
  const lines = [];
  const seq = parseInt(song.sequence) || 1;
  const songName = (song.name || '(untitled)').trim().replace(/"/g, '\\"');
  lines.push(`  {name="${songName}", seq=${seq}, cues={`);
  song.cues.forEach(cue => {
    if (cue.includeStore === false) return;
    const actions = cue.actions
      .filter(a => a.group && a.group.trim())
      .map(a => {
        const presets = Object.entries(a.presets)
          .filter(([, v]) => v && v.name && String(v.name).trim())
          .map(([k, v]) => {
            const def = defaults[k] || { fade: '', delay: '' };
            const fade  = (v.fade  != null && String(v.fade).trim()  !== '') ? v.fade  : def.fade;
            const delay = (v.delay != null && String(v.delay).trim() !== '') ? v.delay : def.delay;
            const parts = [`name="${String(v.name).trim().replace(/"/g, '\\"')}"`];
            if (fade  != null && String(fade).trim()  !== '') parts.push(`fade=${fade}`);
            if (delay != null && String(delay).trim() !== '') parts.push(`delay=${delay}`);
            return `${k}={${parts.join(', ')}}`;
          })
          .join(', ');
        return `      {group="${a.group.trim().replace(/"/g, '\\"')}", presets={${presets}}},`;
      });

    let header = `    {n=${cue.n}, name="${(cue.name || '').trim().replace(/"/g, '\\"')}"`;
    if (cue.fade && String(cue.fade).trim()) header += `, fade=${cue.fade}`;
    if (cue.delay && String(cue.delay).trim()) header += `, delay=${cue.delay}`;
    const note = sanitizeNote(cue.notes);
    if (note) header += `, note="${note}"`;
    if (actions.length === 0) {
      lines.push(header + ', actions={}},');
    } else {
      lines.push(header + ', actions={');
      actions.forEach(a => lines.push(a));
      lines.push('    }},');
    }
  });
  lines.push('  }},');
  return lines;
}

function buildLua(songs, headerTitle) {
  const mode = (state.storeMode === 'Merge') ? 'Merge' : 'Overwrite';
  const lines = [];
  lines.push('-- Generated by Cuelist Compiler');
  lines.push(`-- ${headerTitle}`);
  lines.push(`-- Generated: ${new Date().toISOString()}`);
  lines.push(`-- Store mode: ${mode}`);
  lines.push('-- WARNING: this plugin runs ClearAll before each cue. Run with an empty programmer.');
  lines.push('');
  lines.push('local POOL = {dimmer=1, position=2, gobo=3, color=4, beam=5, focus=6}');
  lines.push(`local STORE_FLAG = "/${mode}"`);
  lines.push('');
  lines.push('local SONGS = {');
  songs.forEach(song => {
    songToLuaEntry(song).forEach(l => lines.push(l));
  });
  lines.push('}');
  lines.push('');
  lines.push('local function main()');
  lines.push('  for _, song in ipairs(SONGS) do');
  lines.push('    Printf("Cuelist Compiler: storing \\""..song.name.."\\" in Sequence "..song.seq)');
  lines.push('    for _, c in ipairs(song.cues) do');
  lines.push('      Cmd("ClearAll")');
  lines.push('      for _, a in ipairs(c.actions) do');
  lines.push('        Cmd(\'Group "\'..a.group..\'"\')');
  lines.push('        for pool, p in pairs(a.presets) do');
  lines.push('          Cmd(\'At Preset \'..POOL[pool]..\'."\'..p.name..\'"\')');
  lines.push('          if p.fade  then Cmd(\'Fade \'..p.fade..\' FeatureGroup \'..POOL[pool])   end');
  lines.push('          if p.delay then Cmd(\'Delay \'..p.delay..\' FeatureGroup \'..POOL[pool]) end');
  lines.push('        end');
  lines.push('      end');
  lines.push('      if c.name ~= "" then');
  lines.push('        Cmd(\'Store Sequence \'..song.seq..\' Cue \'..c.n..\' "\'..c.name..\'" \'..STORE_FLAG..\' /NoConfirmation\')');
  lines.push('      else');
  lines.push('        Cmd(\'Store Sequence \'..song.seq..\' Cue \'..c.n..\' \'..STORE_FLAG..\' /NoConfirmation\')');
  lines.push('      end');
  lines.push('      if c.fade  then Cmd(\'Set Sequence \'..song.seq..\' Cue \'..c.n..\' Fade \'..c.fade)   end');
  lines.push('      if c.delay then Cmd(\'Set Sequence \'..song.seq..\' Cue \'..c.n..\' Delay \'..c.delay) end');
  lines.push('      if c.note  then Cmd(\'Set Sequence \'..song.seq..\' Cue \'..c.n..\' "Note" "\'..c.note..\'"\') end');
  lines.push('    end');
  lines.push('  end');
  lines.push('  Cmd("ClearAll")');
  lines.push('  Printf("Cuelist Compiler: done.")');
  lines.push('end');
  lines.push('');
  lines.push('return main');
  return lines.join('\n');
}

// Mirror of the runtime loop emitted by buildLua's main() — returns the actual
// command-line strings that would be passed to Cmd(). Used by the OSC sender.
// Keep in sync with buildLua's main() above.
function buildCmdLines(songs) {
  const mode = (state.storeMode === 'Merge') ? 'Merge' : 'Overwrite';
  const STORE_FLAG = '/' + mode;
  const out = [];
  songs.forEach(song => {
    const seq = parseInt(song.sequence) || 1;
    (song.cues || []).forEach(cue => {
      if (cue.includeStore === false) return;
      out.push('ClearAll');
      const actions = (cue.actions || []).filter(a => a.group && a.group.trim());
      actions.forEach(a => {
        const groupName = a.group.trim().replace(/"/g, '\\"');
        out.push(`Group "${groupName}"`);
        POOLS.forEach(pool => {
          const p = a.presets[pool];
          if (!p || !p.name || !String(p.name).trim()) return;
          const presetName = String(p.name).trim().replace(/"/g, '\\"');
          out.push(`At Preset ${POOL_NUM[pool]}."${presetName}"`);
          const def = defaults[pool] || { fade: '', delay: '' };
          const fade  = (p.fade  != null && String(p.fade).trim()  !== '') ? p.fade  : def.fade;
          const delay = (p.delay != null && String(p.delay).trim() !== '') ? p.delay : def.delay;
          if (fade  != null && String(fade).trim()  !== '') out.push(`Fade ${fade} FeatureGroup ${POOL_NUM[pool]}`);
          if (delay != null && String(delay).trim() !== '') out.push(`Delay ${delay} FeatureGroup ${POOL_NUM[pool]}`);
        });
      });
      const cueName = (cue.name || '').trim().replace(/"/g, '\\"');
      if (cueName) {
        out.push(`Store Sequence ${seq} Cue ${cue.n} "${cueName}" ${STORE_FLAG} /NoConfirmation`);
      } else {
        out.push(`Store Sequence ${seq} Cue ${cue.n} ${STORE_FLAG} /NoConfirmation`);
      }
      if (cue.fade  && String(cue.fade).trim())  out.push(`Set Sequence ${seq} Cue ${cue.n} Fade ${cue.fade}`);
      if (cue.delay && String(cue.delay).trim()) out.push(`Set Sequence ${seq} Cue ${cue.n} Delay ${cue.delay}`);
      const note = sanitizeNote(cue.notes);
      if (note) out.push(`Set Sequence ${seq} Cue ${cue.n} "Note" "${note}"`);
    });
  });
  out.push('ClearAll');
  return out;
}

// Timecode events — see shared/ma3-command-spec.md §"Timecode show per song".
// Events on MA3 are NOT addressable via command-line `Store Timecode ...` syntax;
// that path only manipulates pool entries. Events require the Lua Object API
// (forum thread 68641). We emit one `Lua "<code>"` command per song that
// MA3 executes via the `Lua` keyword on the command line. Object hierarchy:
// Timecode → TrackGroup → Track → TimeRange → CmdSubTrack → Event. Events
// have `rawtime` (1 s = 16777216 internal units) and `cuedestination` (Cue handle).
// Pre-conditions (operator manual on MA3): Sequence N exists with cues, Timecode
// pool N exists, TrackGroup with at least one Track targeting Sequence N exists.
// Overwrite-only: wipes all existing TimeRanges on the target Track, then rebuilds.
const TC_RAW_PER_SEC = 16777216;

function tcRawtime(positionSmpte) {
  return Math.round(timecodeToSeconds(positionSmpte) * TC_RAW_PER_SEC);
}

function buildTcCmdLines(songs) {
  const out = [];
  (songs || []).forEach(song => {
    const seq = parseInt(song.sequence) || 1;
    const validCues = (song.cues || [])
      .filter(c => c.includeTc !== false)
      .filter(c => isValidSmpte(c.position))
      .slice()
      .sort((a, b) => (parseFloat(a.n) || 0) - (parseFloat(b.n) || 0));
    if (validCues.length === 0) return;

    const cuesLit = validCues.map(c => `{${c.n},${tcRawtime(c.position)}}`).join(',');

    // Single-line Lua (semicolon-separated). Single quotes only — no inner double quotes
    // so the outer `Lua "..."` wrapper parses cleanly through OSC and MA3's command line.
    // tg[2] (not tg[1]) is the first user Track inside the TrackGroup. Index 1 of a
    // TrackGroup is an internal pseudo-track that renders on the TG header row in the
    // Timecode editor; storing events there visually attaches them to the TG, not to
    // the Sequence-targeted Track the operator created. Source: MA forum thread 68641.
    //
    // Overwrite by clearing EVENTS, not TimeRanges. Two API facts proven on a real
    // desk (2026-06-06): TimeRanges are structural and refuse deletion ("deletion of
    // the child object is prohibited"), and Delete is `parent:Delete(1-basedIndex)` —
    // a no-arg `child:Delete()` errors with "Wrong parameter #2". So we walk every
    // TimeRange's CmdSubTrack(s) and delete their event children, then write fresh
    // events into a CmdSubTrack. Events are user content and ARE deletable.
    const lua = [
      `local s=DataPool().sequences[${seq}]`,
      `local t=DataPool().timecodes[${seq}]`,
      `if not s or not t then return end`,
      `local tg=t:Children()[1]`,
      `if not tg then return end`,
      `local tr=tg[2]`,
      `if not tr then return end`,
      `for _,r in ipairs(tr:Children()) do for _,sb in ipairs(r:Children()) do local ev=sb:Children() for i=#ev,1,-1 do sb:Delete(i) end end end`,
      `local rng=tr:Acquire()`,
      `local sub=rng:Acquire('CmdSubTrack')`,
      `for _,c in ipairs({${cuesLit}}) do local e=sub:Acquire() e:Set('rawtime',c[2]) local cue=GetObject('Sequence ${seq} Cue '..c[1]) if cue then e:Set('cuedestination',cue) end end`,
    ].join(';');

    out.push(`Lua "${lua}"`);
  });
  return out;
}

function exportLua() {
  const song = activeSong();
  if (!song || song.cues.length === 0) {
    alert('No cues to export in the active song.');
    return;
  }
  const content = buildLua([song], `Song: ${song.name || '(untitled)'}`);
  const filename = (song.name || 'song').replace(/[^a-zA-Z0-9_\-]+/g, '_') + '.lua';
  download(content, filename, 'text/plain');
}

function exportAllLua() {
  const songs = state.songs.filter(s => s.cues.length > 0);
  if (songs.length === 0) {
    alert('No cues in any song to export.');
    return;
  }
  const content = buildLua(songs, `Show: ${songs.length} song(s)`);
  download(content, 'show.lua', 'text/plain');
}

function buildTcLua(songs, headerTitle) {
  const validSongs = (songs || []).map(song => {
    const seq = parseInt(song.sequence) || 1;
    const cues = (song.cues || [])
      .filter(c => c.includeTc !== false)
      .filter(c => isValidSmpte(c.position))
      .slice()
      .sort((a, b) => (parseFloat(a.n) || 0) - (parseFloat(b.n) || 0));
    return { seq, cues };
  }).filter(x => x.cues.length > 0);

  const lines = [];
  lines.push('-- Generated by Cuelist Compiler — TIMECODE EVENTS (Object API)');
  lines.push(`-- ${headerTitle}`);
  lines.push(`-- Generated: ${new Date().toISOString()}`);
  lines.push('-- PRE-CONDITIONS:');
  lines.push('--   * Sequence <seq> exists with cues.');
  lines.push('--   * Timecode pool <seq> exists.');
  lines.push('--   * TC <seq> has a TrackGroup with at least one Track (target=Sequence <seq>).');
  lines.push('-- BEHAVIOR: clears all existing events on the target Track, then writes fresh ones.');
  lines.push('');
  lines.push('local function applySong(seq, cues)');
  lines.push('  local s = DataPool().sequences[seq]');
  lines.push('  local t = DataPool().timecodes[seq]');
  lines.push('  if not s then Printf("Cuelist TC: Sequence "..seq.." not found"); return end');
  lines.push('  if not t then Printf("Cuelist TC: Timecode pool "..seq.." not found"); return end');
  lines.push('  local tg = t:Children()[1]');
  lines.push('  if not tg then Printf("Cuelist TC: TC "..seq.." has no TrackGroup"); return end');
  lines.push('  -- tg[2] is the first user Track; tg[1] is an internal pseudo-track');
  lines.push('  -- whose events render on the TG header row (forum thread 68641).');
  lines.push('  local tr = tg[2]');
  lines.push('  if not tr then Printf("Cuelist TC: TC "..seq.." TrackGroup has no user Track"); return end');
  lines.push('  -- Clear existing EVENTS, not TimeRanges: TimeRanges are structural and refuse');
  lines.push('  -- deletion ("deletion of the child object is prohibited"); Delete is');
  lines.push('  -- parent:Delete(1-basedIndex) (a no-arg child :Delete() errors "Wrong parameter #2").');
  lines.push('  for _, r in ipairs(tr:Children()) do');
  lines.push('    for _, sb in ipairs(r:Children()) do');
  lines.push('      local ev = sb:Children()');
  lines.push('      for i = #ev, 1, -1 do sb:Delete(i) end');
  lines.push('    end');
  lines.push('  end');
  lines.push('  local rng = tr:Acquire()');
  lines.push('  local sub = rng:Acquire("CmdSubTrack")');
  lines.push('  for _, c in ipairs(cues) do');
  lines.push('    local e = sub:Acquire()');
  lines.push('    e:Set("rawtime", c[2])');
  lines.push('    local cue = GetObject("Sequence "..seq.." Cue "..c[1])');
  lines.push('    if cue then e:Set("cuedestination", cue) end');
  lines.push('  end');
  lines.push('  Printf("Cuelist TC: applied "..#cues.." events to Sequence "..seq)');
  lines.push('end');
  lines.push('');
  lines.push('local SONGS = {');
  validSongs.forEach(s => {
    const cuesLit = s.cues.map(c => `{${c.n},${tcRawtime(c.position)}}`).join(', ');
    lines.push(`  { seq=${s.seq}, cues={${cuesLit}} },`);
  });
  lines.push('}');
  lines.push('');
  lines.push('local function main()');
  lines.push('  for _, song in ipairs(SONGS) do applySong(song.seq, song.cues) end');
  lines.push('end');
  lines.push('');
  lines.push('return main');
  return lines.join('\n');
}

function exportTcLua() {
  const song = activeSong();
  if (!song) return;
  const lines = buildTcCmdLines([song]);
  if (lines.length === 0) { alert('No cues with a valid TC position in the active song.'); return; }
  const content = buildTcLua([song], `Song TC: ${song.name || '(untitled)'}`);
  const filename = (song.name || 'song').replace(/[^a-zA-Z0-9_\-]+/g, '_') + '.tc.lua';
  download(content, filename, 'text/plain');
}

function exportAllTcLua() {
  const songs = state.songs.filter(s => (s.cues || []).some(c => isValidSmpte(c.position)));
  if (songs.length === 0) { alert('No songs have any cues with a valid TC position.'); return; }
  const content = buildTcLua(songs, `Show TC: ${songs.length} song(s)`);
  download(content, 'show.tc.lua', 'text/plain');
}

// --- public surface
window.CC = window.CC || {};
window.CC.compile = { songToLuaEntry, buildLua, buildCmdLines, buildTcCmdLines, buildTcLua, exportLua, exportAllLua, exportTcLua, exportAllTcLua };
