// compile.js — SINGLE SOURCE OF TRUTH for the MA3 command sequence.
// buildLua() (exported .lua plugin) and buildCmdLines() (live OSC) MUST emit the
// same sequence. Any change here must also update shared/ma3-command-spec.md in
// the same PR. Depends on: constants (POOLS, POOL_NUM), state, util (download).

function songToLuaEntry(song) {
  const lines = [];
  const seq = parseInt(song.sequence) || 1;
  const songName = (song.name || '(untitled)').trim().replace(/"/g, '\\"');
  lines.push(`  {name="${songName}", seq=${seq}, cues={`);
  song.cues.forEach(cue => {
    const actions = cue.actions
      .filter(a => a.group && a.group.trim())
      .map(a => {
        const presets = Object.entries(a.presets)
          .filter(([, v]) => v && v.name && String(v.name).trim())
          .map(([k, v]) => {
            const def = defaults[k] || { fade: '', delay: '' };
            const fade  = (v.fade  != null && String(v.fade).trim()  !== '') ? v.fade  : def.fade;
            const delay = (v.delay != null && String(v.delay).trim() !== '') ? v.delay : def.delay;
            const parts = [`name="${String(v.name).trim().replace(/"/g, '\\"')}"`];
            if (fade  != null && String(fade).trim()  !== '') parts.push(`fade=${fade}`);
            if (delay != null && String(delay).trim() !== '') parts.push(`delay=${delay}`);
            return `${k}={${parts.join(', ')}}`;
          })
          .join(', ');
        return `      {group="${a.group.trim().replace(/"/g, '\\"')}", presets={${presets}}},`;
      });

    let header = `    {n=${cue.n}, name="${(cue.name || '').trim().replace(/"/g, '\\"')}"`;
    if (cue.fade && String(cue.fade).trim()) header += `, fade=${cue.fade}`;
    if (cue.delay && String(cue.delay).trim()) header += `, delay=${cue.delay}`;
    if (actions.length === 0) {
      lines.push(header + ', actions={}},');
    } else {
      lines.push(header + ', actions={');
      actions.forEach(a => lines.push(a));
      lines.push('    }},');
    }
  });
  lines.push('  }},');
  return lines;
}

function buildLua(songs, headerTitle) {
  const mode = (state.storeMode === 'Merge') ? 'Merge' : 'Overwrite';
  const lines = [];
  lines.push('-- Generated by Cuelist Compiler');
  lines.push(`-- ${headerTitle}`);
  lines.push(`-- Generated: ${new Date().toISOString()}`);
  lines.push(`-- Store mode: ${mode}`);
  lines.push('-- WARNING: this plugin runs ClearAll before each cue. Run with an empty programmer.');
  lines.push('');
  lines.push('local POOL = {dimmer=1, position=2, gobo=3, color=4, beam=5, focus=6}');
  lines.push(`local STORE_FLAG = "/${mode}"`);
  lines.push('');
  lines.push('local SONGS = {');
  songs.forEach(song => {
    songToLuaEntry(song).forEach(l => lines.push(l));
  });
  lines.push('}');
  lines.push('');
  lines.push('local function main()');
  lines.push('  for _, song in ipairs(SONGS) do');
  lines.push('    Printf("Cuelist Compiler: storing \\""..song.name.."\\" in Sequence "..song.seq)');
  lines.push('    for _, c in ipairs(song.cues) do');
  lines.push('      Cmd("ClearAll")');
  lines.push('      for _, a in ipairs(c.actions) do');
  lines.push('        Cmd(\'Group "\'..a.group..\'"\')');
  lines.push('        for pool, p in pairs(a.presets) do');
  lines.push('          Cmd(\'At Preset \'..POOL[pool]..\'."\'..p.name..\'"\')');
  lines.push('          if p.fade  then Cmd(\'Fade \'..p.fade..\' FeatureGroup \'..POOL[pool])   end');
  lines.push('          if p.delay then Cmd(\'Delay \'..p.delay..\' FeatureGroup \'..POOL[pool]) end');
  lines.push('        end');
  lines.push('      end');
  lines.push('      if c.name ~= "" then');
  lines.push('        Cmd(\'Store Sequence \'..song.seq..\' Cue \'..c.n..\' "\'..c.name..\'" \'..STORE_FLAG..\' /NoConfirmation\')');
  lines.push('      else');
  lines.push('        Cmd(\'Store Sequence \'..song.seq..\' Cue \'..c.n..\' \'..STORE_FLAG..\' /NoConfirmation\')');
  lines.push('      end');
  lines.push('      if c.fade  then Cmd(\'Set Sequence \'..song.seq..\' Cue \'..c.n..\' Fade \'..c.fade)   end');
  lines.push('      if c.delay then Cmd(\'Set Sequence \'..song.seq..\' Cue \'..c.n..\' Delay \'..c.delay) end');
  lines.push('    end');
  lines.push('  end');
  lines.push('  Cmd("ClearAll")');
  lines.push('  Printf("Cuelist Compiler: done.")');
  lines.push('end');
  lines.push('');
  lines.push('return main');
  return lines.join('\n');
}

// Mirror of the runtime loop emitted by buildLua's main() — returns the actual
// command-line strings that would be passed to Cmd(). Used by the OSC sender.
// Keep in sync with buildLua's main() above.
function buildCmdLines(songs) {
  const mode = (state.storeMode === 'Merge') ? 'Merge' : 'Overwrite';
  const STORE_FLAG = '/' + mode;
  const out = [];
  songs.forEach(song => {
    const seq = parseInt(song.sequence) || 1;
    (song.cues || []).forEach(cue => {
      out.push('ClearAll');
      const actions = (cue.actions || []).filter(a => a.group && a.group.trim());
      actions.forEach(a => {
        const groupName = a.group.trim().replace(/"/g, '\\"');
        out.push(`Group "${groupName}"`);
        POOLS.forEach(pool => {
          const p = a.presets[pool];
          if (!p || !p.name || !String(p.name).trim()) return;
          const presetName = String(p.name).trim().replace(/"/g, '\\"');
          out.push(`At Preset ${POOL_NUM[pool]}."${presetName}"`);
          const def = defaults[pool] || { fade: '', delay: '' };
          const fade  = (p.fade  != null && String(p.fade).trim()  !== '') ? p.fade  : def.fade;
          const delay = (p.delay != null && String(p.delay).trim() !== '') ? p.delay : def.delay;
          if (fade  != null && String(fade).trim()  !== '') out.push(`Fade ${fade} FeatureGroup ${POOL_NUM[pool]}`);
          if (delay != null && String(delay).trim() !== '') out.push(`Delay ${delay} FeatureGroup ${POOL_NUM[pool]}`);
        });
      });
      const cueName = (cue.name || '').trim().replace(/"/g, '\\"');
      if (cueName) {
        out.push(`Store Sequence ${seq} Cue ${cue.n} "${cueName}" ${STORE_FLAG} /NoConfirmation`);
      } else {
        out.push(`Store Sequence ${seq} Cue ${cue.n} ${STORE_FLAG} /NoConfirmation`);
      }
      if (cue.fade  && String(cue.fade).trim())  out.push(`Set Sequence ${seq} Cue ${cue.n} Fade ${cue.fade}`);
      if (cue.delay && String(cue.delay).trim()) out.push(`Set Sequence ${seq} Cue ${cue.n} Delay ${cue.delay}`);
    });
  });
  out.push('ClearAll');
  return out;
}

// Timecode events — see shared/ma3-command-spec.md §"Timecode show per song".
// Pre-conditions (operator manual): Sequence N, TC pool N, and Track at .1.1
// with target=Sequence N must exist on MA3. Overwrite-only behavior: wipes
// existing events at <N>.1.1.1.1 with up to 200 deletes (excess fail silently).
function buildTcCmdLines(songs) {
  const out = [];
  (songs || []).forEach(song => {
    const seq = parseInt(song.sequence) || 1;
    const validCues = (song.cues || [])
      .filter(c => isValidSmpte(c.position))
      .slice()
      .sort((a, b) => (parseFloat(a.n) || 0) - (parseFloat(b.n) || 0));
    if (validCues.length === 0) return;
    for (let i = 0; i < 200; i++) {
      out.push(`Delete Timecode ${seq}.1.1.1.1.1 /NoConfirmation`);
    }
    validCues.forEach((cue, i) => {
      const eventIdx = i + 1;
      const seconds = timecodeToSeconds(cue.position);
      const sStr = Number.isInteger(seconds)
        ? String(seconds)
        : String(+seconds.toFixed(6)).replace(/\.?0+$/, '');
      out.push(`Store Timecode ${seq}.1.1.1.1 'Goto Cue ${cue.n} Sequence ${seq}' /NoConfirmation`);
      out.push(`Set Timecode ${seq}.1.1.1.1.${eventIdx} Property 'time' ${sStr}`);
    });
  });
  return out;
}

function exportLua() {
  const song = activeSong();
  if (!song || song.cues.length === 0) {
    alert('No cues to export in the active song.');
    return;
  }
  const content = buildLua([song], `Song: ${song.name || '(untitled)'}`);
  const filename = (song.name || 'song').replace(/[^a-zA-Z0-9_\-]+/g, '_') + '.lua';
  download(content, filename, 'text/plain');
}

function exportAllLua() {
  const songs = state.songs.filter(s => s.cues.length > 0);
  if (songs.length === 0) {
    alert('No cues in any song to export.');
    return;
  }
  const content = buildLua(songs, `Show: ${songs.length} song(s)`);
  download(content, 'show.lua', 'text/plain');
}

function buildTcLua(songs, headerTitle) {
  const cmds = buildTcCmdLines(songs);
  const lines = [];
  lines.push('-- Generated by Cuelist Compiler — TIMECODE EVENTS');
  lines.push(`-- ${headerTitle}`);
  lines.push(`-- Generated: ${new Date().toISOString()}`);
  lines.push('-- PRE-CONDITION: TC pool + Track (target=Sequence) must exist on MA3.');
  lines.push('-- BEHAVIOR: deletes up to 200 existing events per song, then adds new ones.');
  lines.push('');
  lines.push('local function main()');
  lines.push(`  Printf("Cuelist Compiler TC: applying " .. ${cmds.length} .. " commands")`);
  cmds.forEach(line => {
    const escaped = line.replace(/'/g, "\\'");
    lines.push(`  Cmd('${escaped}')`);
  });
  lines.push('  Printf("Cuelist Compiler TC: done.")');
  lines.push('end');
  lines.push('');
  lines.push('return main');
  return lines.join('\n');
}

function exportTcLua() {
  const song = activeSong();
  if (!song) return;
  const lines = buildTcCmdLines([song]);
  if (lines.length === 0) { alert('No cues with a valid TC position in the active song.'); return; }
  const content = buildTcLua([song], `Song TC: ${song.name || '(untitled)'}`);
  const filename = (song.name || 'song').replace(/[^a-zA-Z0-9_\-]+/g, '_') + '.tc.lua';
  download(content, filename, 'text/plain');
}

function exportAllTcLua() {
  const songs = state.songs.filter(s => (s.cues || []).some(c => isValidSmpte(c.position)));
  if (songs.length === 0) { alert('No songs have any cues with a valid TC position.'); return; }
  const content = buildTcLua(songs, `Show TC: ${songs.length} song(s)`);
  download(content, 'show.tc.lua', 'text/plain');
}

// --- public surface
window.CC = window.CC || {};
window.CC.compile = { songToLuaEntry, buildLua, buildCmdLines, buildTcCmdLines, buildTcLua, exportLua, exportAllLua, exportTcLua, exportAllTcLua };
