// compile.js — SINGLE SOURCE OF TRUTH for the MA3 command sequence.
// buildLua() (exported .lua plugin) and buildCmdLines() (live OSC) MUST emit the
// same sequence. Any change here must also update shared/ma3-command-spec.md in
// the same PR. Depends on: constants (POOLS, POOL_NUM), state, util (download).

// Collapse a free-text (often voice-captured, multi-line) note into one safe
// command-line token: newlines/tabs/runs of whitespace → single space, trimmed,
// then " escaped to \". Returns '' for null/empty/whitespace-only input.
function sanitizeNote(raw) {
  return String(raw == null ? '' : raw)
    .replace(/[\r\n\t]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/"/g, '\\"');
}

function songToLuaEntry(song) {
  const lines = [];
  const seq = parseInt(song.sequence) || 1;
  const songName = (song.name || '(untitled)').trim().replace(/"/g, '\\"');
  lines.push(`  {name="${songName}", seq=${seq}, cues={`);
  song.cues.forEach(cue => {
    const actions = cue.actions
      .filter(a => a.group && a.group.trim())
      .map(a => {
        const presets = Object.entries(a.presets)
          .filter(([, v]) => v && v.name && String(v.name).trim())
          .map(([k, v]) => {
            const def = defaults[k] || { fade: '', delay: '' };
            const fade  = (v.fade  != null && String(v.fade).trim()  !== '') ? v.fade  : def.fade;
            const delay = (v.delay != null && String(v.delay).trim() !== '') ? v.delay : def.delay;
            const parts = [`name="${String(v.name).trim().replace(/"/g, '\\"')}"`];
            if (fade  != null && String(fade).trim()  !== '') parts.push(`fade=${fade}`);
            if (delay != null && String(delay).trim() !== '') parts.push(`delay=${delay}`);
            return `${k}={${parts.join(', ')}}`;
          })
          .join(', ');
        return `      {group="${a.group.trim().replace(/"/g, '\\"')}", presets={${presets}}},`;
      });

    let header = `    {n=${cue.n}, name="${(cue.name || '').trim().replace(/"/g, '\\"')}"`;
    if (cue.fade && String(cue.fade).trim()) header += `, fade=${cue.fade}`;
    if (cue.delay && String(cue.delay).trim()) header += `, delay=${cue.delay}`;
    if (actions.length === 0) {
      lines.push(header + ', actions={}},');
    } else {
      lines.push(header + ', actions={');
      actions.forEach(a => lines.push(a));
      lines.push('    }},');
    }
  });
  lines.push('  }},');
  return lines;
}

function buildLua(songs, headerTitle) {
  const mode = (state.storeMode === 'Merge') ? 'Merge' : 'Overwrite';
  const lines = [];
  lines.push('-- Generated by Cuelist Compiler');
  lines.push(`-- ${headerTitle}`);
  lines.push(`-- Generated: ${new Date().toISOString()}`);
  lines.push(`-- Store mode: ${mode}`);
  lines.push('-- WARNING: this plugin runs ClearAll before each cue. Run with an empty programmer.');
  lines.push('');
  lines.push('local POOL = {dimmer=1, position=2, gobo=3, color=4, beam=5, focus=6}');
  lines.push(`local STORE_FLAG = "/${mode}"`);
  lines.push('');
  lines.push('local SONGS = {');
  songs.forEach(song => {
    songToLuaEntry(song).forEach(l => lines.push(l));
  });
  lines.push('}');
  lines.push('');
  lines.push('local function main()');
  lines.push('  for _, song in ipairs(SONGS) do');
  lines.push('    Printf("Cuelist Compiler: storing \\""..song.name.."\\" in Sequence "..song.seq)');
  lines.push('    for _, c in ipairs(song.cues) do');
  lines.push('      Cmd("ClearAll")');
  lines.push('      for _, a in ipairs(c.actions) do');
  lines.push('        Cmd(\'Group "\'..a.group..\'"\')');
  lines.push('        for pool, p in pairs(a.presets) do');
  lines.push('          Cmd(\'At Preset \'..POOL[pool]..\'."\'..p.name..\'"\')');
  lines.push('          if p.fade  then Cmd(\'Fade \'..p.fade..\' FeatureGroup \'..POOL[pool])   end');
  lines.push('          if p.delay then Cmd(\'Delay \'..p.delay..\' FeatureGroup \'..POOL[pool]) end');
  lines.push('        end');
  lines.push('      end');
  lines.push('      if c.name ~= "" then');
  lines.push('        Cmd(\'Store Sequence \'..song.seq..\' Cue \'..c.n..\' "\'..c.name..\'" \'..STORE_FLAG..\' /NoConfirmation\')');
  lines.push('      else');
  lines.push('        Cmd(\'Store Sequence \'..song.seq..\' Cue \'..c.n..\' \'..STORE_FLAG..\' /NoConfirmation\')');
  lines.push('      end');
  lines.push('      if c.fade  then Cmd(\'Set Sequence \'..song.seq..\' Cue \'..c.n..\' Fade \'..c.fade)   end');
  lines.push('      if c.delay then Cmd(\'Set Sequence \'..song.seq..\' Cue \'..c.n..\' Delay \'..c.delay) end');
  lines.push('    end');
  lines.push('  end');
  lines.push('  Cmd("ClearAll")');
  lines.push('  Printf("Cuelist Compiler: done.")');
  lines.push('end');
  lines.push('');
  lines.push('return main');
  return lines.join('\n');
}

// Mirror of the runtime loop emitted by buildLua's main() — returns the actual
// command-line strings that would be passed to Cmd(). Used by the OSC sender.
// Keep in sync with buildLua's main() above.
function buildCmdLines(songs) {
  const mode = (state.storeMode === 'Merge') ? 'Merge' : 'Overwrite';
  const STORE_FLAG = '/' + mode;
  const out = [];
  songs.forEach(song => {
    const seq = parseInt(song.sequence) || 1;
    (song.cues || []).forEach(cue => {
      out.push('ClearAll');
      const actions = (cue.actions || []).filter(a => a.group && a.group.trim());
      actions.forEach(a => {
        const groupName = a.group.trim().replace(/"/g, '\\"');
        out.push(`Group "${groupName}"`);
        POOLS.forEach(pool => {
          const p = a.presets[pool];
          if (!p || !p.name || !String(p.name).trim()) return;
          const presetName = String(p.name).trim().replace(/"/g, '\\"');
          out.push(`At Preset ${POOL_NUM[pool]}."${presetName}"`);
          const def = defaults[pool] || { fade: '', delay: '' };
          const fade  = (p.fade  != null && String(p.fade).trim()  !== '') ? p.fade  : def.fade;
          const delay = (p.delay != null && String(p.delay).trim() !== '') ? p.delay : def.delay;
          if (fade  != null && String(fade).trim()  !== '') out.push(`Fade ${fade} FeatureGroup ${POOL_NUM[pool]}`);
          if (delay != null && String(delay).trim() !== '') out.push(`Delay ${delay} FeatureGroup ${POOL_NUM[pool]}`);
        });
      });
      const cueName = (cue.name || '').trim().replace(/"/g, '\\"');
      if (cueName) {
        out.push(`Store Sequence ${seq} Cue ${cue.n} "${cueName}" ${STORE_FLAG} /NoConfirmation`);
      } else {
        out.push(`Store Sequence ${seq} Cue ${cue.n} ${STORE_FLAG} /NoConfirmation`);
      }
      if (cue.fade  && String(cue.fade).trim())  out.push(`Set Sequence ${seq} Cue ${cue.n} Fade ${cue.fade}`);
      if (cue.delay && String(cue.delay).trim()) out.push(`Set Sequence ${seq} Cue ${cue.n} Delay ${cue.delay}`);
      const note = sanitizeNote(cue.notes);
      if (note) out.push(`Set Sequence ${seq} Cue ${cue.n} "Note" "${note}"`);
    });
  });
  out.push('ClearAll');
  return out;
}

function exportLua() {
  const song = activeSong();
  if (!song || song.cues.length === 0) {
    alert('No cues to export in the active song.');
    return;
  }
  const content = buildLua([song], `Song: ${song.name || '(untitled)'}`);
  const filename = (song.name || 'song').replace(/[^a-zA-Z0-9_\-]+/g, '_') + '.lua';
  download(content, filename, 'text/plain');
}

function exportAllLua() {
  const songs = state.songs.filter(s => s.cues.length > 0);
  if (songs.length === 0) {
    alert('No cues in any song to export.');
    return;
  }
  const content = buildLua(songs, `Show: ${songs.length} song(s)`);
  download(content, 'show.lua', 'text/plain');
}

// --- public surface
window.CC = window.CC || {};
CC.compile = { songToLuaEntry, buildLua, buildCmdLines, exportLua, exportAllLua };
