-- Generated by Cuelist Compiler
-- Song: SONG 1
-- Generated: 2026-05-31T20:30:13.804Z
-- WARNING: this plugin runs ClearAll before each cue. Run with an empty programmer.

local POOL = {dimmer=1, position=2, gobo=3, color=4, beam=5, focus=6}

local SEQ = 667

local CUES = {
  {n=0.1, name="DB CUE", fade=5, actions={
    {group="AROLLA FLOOR", presets={color={name="BLUE", fade=0.4}, dimmer={name="DIMMER 100", fade=0.3}, position={name="LOW", fade=10}, focus={name="MEDIUM"}}},
  }},
  {n=1, name="INTRO", actions={
    {group="AROLLA FLOOR", presets={color={name="RED", fade=1}, dimmer={name="DIMMER 0", fade=1}, position={name="AUD", fade=9}, focus={name="WIDE"}}},
  }},
}

local function main()
  for _, c in ipairs(CUES) do
    Cmd("ClearAll")
    for _, a in ipairs(c.actions) do
      Cmd('Group "'..a.group..'"')
      for pool, p in pairs(a.presets) do
        Cmd('At Preset '..POOL[pool]..'."'..p.name..'"')
        if p.fade  then Cmd('Fade '..p.fade..' FeatureGroup '..POOL[pool])   end
        if p.delay then Cmd('Delay '..p.delay..' FeatureGroup '..POOL[pool]) end
      end
    end
    if c.name ~= "" then
      Cmd('Store Sequence '..SEQ..' Cue '..c.n..' "'..c.name..'" /Overwrite /NoConfirmation')
    else
      Cmd('Store Sequence '..SEQ..' Cue '..c.n..' /Overwrite /NoConfirmation')
    end
    if c.fade  then Cmd('Set Sequence '..SEQ..' Cue '..c.n..' Fade '..c.fade)   end
    if c.delay then Cmd('Set Sequence '..SEQ..' Cue '..c.n..' Delay '..c.delay) end
  end
  Cmd("ClearAll")
  Printf("Cuelist Compiler: stored "..#CUES.." cues in Sequence "..SEQ)
end

return main