-- Generated by Cuelist Compiler
-- Song: SONG 1
-- Generated: 2026-06-04T18:34:53.350Z
-- Store mode: Overwrite
-- WARNING: this plugin runs ClearAll before each cue. Run with an empty programmer.

local POOL = {dimmer=1, position=2, gobo=3, color=4, beam=5, focus=6}
local STORE_FLAG = "/Overwrite"

local SONGS = {
  {name="SONG 1", seq=666, cues={
    {n=0.1, name="DB CUE", fade=5, actions={
      {group="AROLLA FLOOR", presets={color={name="BLUE"}, dimmer={name="DIMMER 100"}, position={name="LOW"}, focus={name="MEDIUM"}}},
    }},
    {n=1, name="INTRO", fade=6, actions={
      {group="AROLLA FLOOR", presets={color={name="RED"}, dimmer={name="DIMMER 0"}, position={name="AUD"}, focus={name="WIDE"}}},
    }},
  }},
}

local function main()
  for _, song in ipairs(SONGS) do
    Printf("Cuelist Compiler: storing \""..song.name.."\" in Sequence "..song.seq)
    for _, c in ipairs(song.cues) do
      Cmd("ClearAll")
      for _, a in ipairs(c.actions) do
        Cmd('Group "'..a.group..'"')
        for pool, p in pairs(a.presets) do
          Cmd('At Preset '..POOL[pool]..'."'..p.name..'"')
          if p.fade  then Cmd('Fade '..p.fade..' FeatureGroup '..POOL[pool])   end
          if p.delay then Cmd('Delay '..p.delay..' FeatureGroup '..POOL[pool]) end
        end
      end
      if c.name ~= "" then
        Cmd('Store Sequence '..song.seq..' Cue '..c.n..' "'..c.name..'" '..STORE_FLAG..' /NoConfirmation')
      else
        Cmd('Store Sequence '..song.seq..' Cue '..c.n..' '..STORE_FLAG..' /NoConfirmation')
      end
      if c.fade  then Cmd('Set Sequence '..song.seq..' Cue '..c.n..' Fade '..c.fade)   end
      if c.delay then Cmd('Set Sequence '..song.seq..' Cue '..c.n..' Delay '..c.delay) end
    end
  end
  Cmd("ClearAll")
  Printf("Cuelist Compiler: done.")
end

return main